# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs


workflows:
  test-env-var:
    jobs:
      - build

jobs:
  build:
    docker:
    - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo my env var that is part of this project"
          command: 
            echo $My_Env_Var 

## Let's try something
