version: 2.1
commands:
  print_pipeline_id:
    description: "Prints out Circle CI Workflow ID from its environment variable"
    parameters:
      id:
        type: string
    steps:
     - run: echo << parameters.id >>





jobs:
  new_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id

workflows:
  my_workflow:
    jobs:
      - new_job


## Let's try something
