# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs




jobs:
  save_hello_world_output:  
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "hello world" > output.txt
      - persist-to-workspace:
          root: ~/
          path:
            - output.txt

  print_output_file:
    docker:
      - image: cimg/base:2020.01 
    steps:   
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

workflows:
  my_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
        requires:
          - save_hello_world_output


## Let's try something
