version: 2.1
jobs:
  my_new_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run:
          name: watch me fail
          command: echo "Hello world"
          when: on_fail


workflows:
  my_workflow:
    jobs:
      - my_new_job


## Let's try something
